[project]
name = "tobench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.13.5",
    "torch",
]

[project.optional-dependencies]
iree = ["iree-turbine>=3.9,<4"]
tvm = ["apache-tvm>=0.26,<0.27"]
tvm-tuning = ["apache-tvm>=0.26,<0.27", "xgboost", "psutil", "cloudpickle"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[dependency-groups]
dev = [
    "ruff>=0.16.7",
]

[tool.ruff]
include = ["src/**/*.py"]

[tool.ruff.lint]
select = ["ANN", "I"]

# too strict/noisy for projects
ignore = [
    "ANN401",  # Allow typing.Any
]
